name: Test Client

on:
  workflow_dispatch:
  pull_request:
    
jobs:
  ui-e2e-test:
    uses: clim-mas/reusableworkflow/.github/workflows/cypress.yml@main
    secrets:
      WORKING_DIRECTORY: web
      TESTRAILS_RUN_NAME: "Cypress Web Test"
      TESTRAIL_PROJECTID: 8
      TESTRAIL_HOST: ${{secrets.TESTRAIL_HOST}}
      TESTRAIL_DOMAIN: ${{secrets.TESTRAIL_DOMAIN}}
      TESTRAIL_USERNAME: ${{secrets.TESTRAIL_USERNAME}}
      TESTRAIL_PASSWORD: ${{secrets.TESTRAIL_PASSWORD}}
      TESTRAIL_APIKEY: ${{secrets.TESTRAIL_PASSWORD}}