name: Test Service

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building Service
        run: echo Hello, I am building the service!
   
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Running Unit Test
        run: echo Hello, I am running the Unit Test!
      
  api-e2e-test:
    needs: unit-test
    uses: clim-mas/reusableworkflow/.github/workflows/postman.yml@main
    secrets:
      COLLECTION_ID: ${{ secrets.COLLECTION_ID }}
      ENVIRONMENT_ID: ${{ secrets.ENVIRONMENT_ID }}
